import {useEffect,useRef,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {FileText,FileSpreadsheet,File,Upload,Trash2,Send,Plus,RefreshCw,Square,Download,CheckCircle2,AlertTriangle,LoaderCircle,ChevronDown,PanelRight,PanelLeft} from 'lucide-react';
import {api,Artifact,Citation,Doc,Task} from './api';

const templates=['总结这些合同的甲乙方、金额、截止日期和风险条款。','比较所有报价单，生成供应商价格汇总。','分析销售数据，找出下降最明显的产品并生成周报。'];
const size=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
function Icon({doc}:{doc:Doc}){return doc.original_name.endsWith('.xlsx')?<FileSpreadsheet/>:doc.original_name.endsWith('.pdf')?<File/>:<FileText/>}
function location(c:Citation){const x=c.location;return x.page?`第 ${x.page} 页`:x.sheet?`${x.sheet} · ${x.range}`:x.paragraph?`第 ${x.paragraph} 段`:'来源片段'}

export default function App(){
 const qc=useQueryClient();const [workspace,setWorkspace]=useState(localStorage.getItem('workspace')||'');const [selected,setSelected]=useState('');const [message,setMessage]=useState('');const [quote,setQuote]=useState<Citation|null>(null);const [mobile,setMobile]=useState<'files'|'chat'|'run'>('chat');const fileInput=useRef<HTMLInputElement>(null);
 const ws=useQuery({queryKey:['workspaces'],queryFn:api.workspaces});
 useEffect(()=>{if(!workspace&&ws.data?.[0])setWorkspace(ws.data[0].id)},[ws.data,workspace]); useEffect(()=>{if(workspace)localStorage.setItem('workspace',workspace)},[workspace]);
 const docs=useQuery({queryKey:['documents',workspace],queryFn:()=>api.documents(workspace),enabled:!!workspace});
 const tasks=useQuery({queryKey:['tasks',workspace],queryFn:()=>api.tasks(workspace),enabled:!!workspace,refetchInterval:q=>q.state.data?.some(t=>['queued','running'].includes(t.status))?1500:false});
 const task=tasks.data?.find(t=>t.id===selected)||tasks.data?.[0];
 useEffect(()=>{if(!selected&&tasks.data?.[0])setSelected(tasks.data[0].id)},[tasks.data,selected]);
 const artifacts=useQuery({queryKey:['artifacts',task?.id],queryFn:()=>api.artifacts(task!.id),enabled:task?.status==='completed'});
 useEffect(()=>{if(!task||!['queued','running'].includes(task.status))return;const es=new EventSource(`/api/tasks/${task.id}/events`);const refresh=()=>{qc.invalidateQueries({queryKey:['tasks',workspace]});qc.invalidateQueries({queryKey:['artifacts',task.id]})};['plan','step','citation','artifact','error','done'].forEach(x=>es.addEventListener(x,refresh));return()=>es.close()},[task?.id,task?.status,qc,workspace]);
 const createWs=useMutation({mutationFn:()=>api.createWorkspace(`新工作区 ${new Date().toLocaleDateString('zh-CN')}`),onSuccess:w=>{setWorkspace(w.id);qc.invalidateQueries({queryKey:['workspaces']})}});
 const upload=useMutation({mutationFn:(files:File[])=>api.upload(workspace,files),onSuccess:()=>qc.invalidateQueries({queryKey:['documents',workspace]})});
 const run=useMutation({mutationFn:()=>api.createTask(workspace,message),onSuccess:t=>{setSelected(t.id);setMessage('');qc.invalidateQueries({queryKey:['tasks',workspace]});setMobile('run')}});
 const stop=useMutation({mutationFn:()=>api.cancel(task!.id),onSuccess:()=>qc.invalidateQueries({queryKey:['tasks',workspace]})});
 const retry=useMutation({mutationFn:()=>api.retry(task!.id),onSuccess:t=>{setSelected(t.id);qc.invalidateQueries({queryKey:['tasks',workspace]})}});
 const currentWs=ws.data?.find(x=>x.id===workspace);
 if(ws.isLoading)return <div className="boot"><LoaderCircle className="spin"/><span>正在打开工作台…</span></div>;
 if(!ws.data?.length)return <main className="welcome"><div className="mark"><FileText/></div><h1>把散落的文件，变成有出处的答案</h1><p>在本机安全分析 PDF、Word 和 Excel。原始文件不会被修改，关键结论都能回到原文。</p><button className="primary big" onClick={()=>createWs.mutate()} disabled={createWs.isPending}><Plus/>创建第一个工作区</button><small>单用户 · 本机 Docker · 支持中英文文档</small></main>;
 return <div className="shell">
  <header><div className="brand"><span className="brandMark"><FileText/></span><strong>案牍</strong><span>办公文档 Agent</span></div><div className="workspaceSelect"><label htmlFor="workspace">工作区</label><select id="workspace" value={workspace} onChange={e=>{setWorkspace(e.target.value);setSelected('')}}>{ws.data?.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><ChevronDown/></div><button className="iconButton" title="新建工作区" onClick={()=>createWs.mutate()}><Plus/></button></header>
  <nav className="mobileNav" aria-label="工作台区域"><button className={mobile==='files'?'active':''} onClick={()=>setMobile('files')}><PanelLeft/>文件</button><button className={mobile==='chat'?'active':''} onClick={()=>setMobile('chat')}><FileText/>对话</button><button className={mobile==='run'?'active':''} onClick={()=>setMobile('run')}><PanelRight/>执行</button></nav>
  <aside className={`filesPane pane mobile-${mobile}`}><div className="paneHead"><div><h2>工作区文件</h2><p>{docs.data?.length||0} 个文件 · {currentWs?.name}</p></div><button className="iconButton" title="上传文件" onClick={()=>fileInput.current?.click()}><Upload/></button></div>
   <input ref={fileInput} hidden type="file" multiple accept=".pdf,.docx,.xlsx" onChange={e=>e.target.files&&upload.mutate([...e.target.files])}/>
   {!docs.data?.length?<button className="dropzone" onClick={()=>fileInput.current?.click()}><Upload/><strong>拖拽或选择文件</strong><span>PDF、DOCX、XLSX · 单个最大 25 MB</span></button>:<div className="fileList">{docs.data.map(d=><div className="fileRow" key={d.id}><span className={`fileIcon ${d.status}`}><Icon doc={d}/></span><div><strong title={d.original_name}>{d.original_name}</strong><span>{size(d.size_bytes)} · {d.page_count?`${d.page_count} 页/表`:d.status}</span></div><span className={`status ${d.status}`}>{d.status==='ready'?'就绪':d.status==='parsing'?'解析中':'失败'}</span><button className="rowAction" title="删除" onClick={()=>api.deleteDocument(d.id).then(()=>qc.invalidateQueries({queryKey:['documents',workspace]}))}><Trash2/></button></div>)}</div>}
   {upload.isPending&&<div className="inlineState"><LoaderCircle className="spin"/>正在校验并解析文件…</div>}{upload.error&&<div className="error"><AlertTriangle/><span>{upload.error.message}</span></div>}
  </aside>
  <main className={`chatPane pane mobile-${mobile}`}><div className="conversationHead"><div><h1>{currentWs?.name}</h1><p>只使用当前工作区中已解析的文档</p></div><span className="privacy"><CheckCircle2/>原文件只读</span></div>
   <div className="conversation">{!tasks.data?.length?<div className="empty"><div className="emptyIcon"><FileText/></div><h2>从一个明确的问题开始</h2><p>我会先展示计划，再检索文档、标记来源并生成可下载的报告。</p><div className="templates">{templates.map(x=><button key={x} onClick={()=>setMessage(x)}>{x}</button>)}</div></div>:tasks.data.map(t=><button key={t.id} className={`history ${task?.id===t.id?'selected':''}`} onClick={()=>setSelected(t.id)}><span>{t.user_message}</span><em className={t.status}>{t.status==='completed'?'已完成':t.status==='running'?'执行中':t.status==='queued'?'排队中':t.status==='failed'?'失败':'已取消'}</em></button>)}
    {task&&<section className="answer"><div className="question"><span>你</span><p>{task.user_message}</p></div>{task.status==='completed'&&task.final_answer_json?<><div className="agentLabel"><span className="brandMark small"><FileText/></span><strong>案牍 Agent</strong></div><p className="summary">{task.final_answer_json.summary}</p><div className="findings">{task.final_answer_json.findings.map((f,i)=><p key={i}>{f.statement} {f.citation_ids.map(id=><button className="cite" key={id} onClick={()=>setQuote(task.final_answer_json!.citations.find(c=>c.id===id)||null)}>[{id}]</button>)}</p>)}</div>{task.final_answer_json.warnings.map(w=><div className="warning" key={w}><AlertTriangle/><span>{w}</span></div>)}</>:task.status==='failed'?<div className="error large"><AlertTriangle/><div><strong>任务执行失败</strong><p>{task.error_message} · {task.error_code}</p><button onClick={()=>retry.mutate()}><RefreshCw/>重新运行</button></div></div>:<div className="thinking"><LoaderCircle className="spin"/><div><strong>{task.status==='queued'?'等待 Worker 领取':'正在处理文档'}</strong><span>执行详情会实时显示在右侧</span></div></div>}</section>}
   </div>
   <form className="composer" onSubmit={e=>{e.preventDefault();if(message.trim()&&!run.isPending)run.mutate()}}><textarea aria-label="任务要求" value={message} onChange={e=>setMessage(e.target.value)} placeholder={docs.data?.length?'描述要总结、比较、分析或生成的内容…':'请先上传至少一份文档'} disabled={!docs.data?.some(d=>d.status==='ready')} rows={3}/><div><span>Enter 发送 · Shift+Enter 换行</span><button className="primary" disabled={!message.trim()||run.isPending||!docs.data?.some(d=>d.status==='ready')}><Send/>{run.isPending?'创建中':'开始任务'}</button></div></form>
  </main>
  <aside className={`runPane pane mobile-${mobile}`}><div className="paneHead"><div><h2>执行详情</h2><p>{task?`任务 ${task.id.slice(0,8)}`:'等待任务'}</p></div>{task&&['queued','running'].includes(task.status)&&<button className="iconButton danger" title="取消任务" onClick={()=>stop.mutate()}><Square/></button>}</div>
   {!task?<div className="sideEmpty"><p>任务开始后，这里会显示计划、步骤、引用、警告和生成文件。</p></div>:<><section className="runSection"><h3>计划</h3><ol className="timeline">{(task.plan_json.length?task.plan_json:['等待生成计划']).map((x,i)=><li key={x} className={task.status==='completed'?'done':i===0?'current':''}><span>{task.status==='completed'?<CheckCircle2/>:i===0?<LoaderCircle className="spin"/>:i+1}</span><p>{x}</p></li>)}</ol></section>{task.final_answer_json?.citations.length?<section className="runSection"><h3>引用 <b>{task.final_answer_json.citations.length}</b></h3><div className="sourceList">{task.final_answer_json.citations.map(c=><button key={c.id} onClick={()=>setQuote(c)}><span>{c.id}</span><div><strong>{c.document_name}</strong><small>{location(c)}</small></div></button>)}</div></section>:null}<section className="runSection"><h3>生成文件</h3>{artifacts.data?.length?<div className="artifactList">{artifacts.data.map((a:Artifact)=><a key={a.id} href={`/api/artifacts/${a.id}/download`}><span><FileText/></span><div><strong>{a.name}</strong><small>{a.type.toUpperCase()} · {size(a.size_bytes)}</small></div><Download/></a>)}</div>:<p className="muted">任务完成后可在此下载产物</p>}</section></>}
  </aside>
  {quote&&<div className="drawerBackdrop" onClick={()=>setQuote(null)}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="drawerClose" onClick={()=>setQuote(null)}>关闭</button><span className="sourceTag">来源 {quote.id}</span><h2>{quote.document_name}</h2><p className="sourceLocation">{location(quote)}</p><blockquote>{quote.quote}</blockquote><p className="drawerNote">引用内容来自解析时保留的真实文档位置。</p></aside></div>}
 </div>
}
